/**
 * Shared climate-zone reference data used by R-Value Calculator and
 * Climate Zone Map pages for SSR-rendered lookup tables. One source
 * of truth so a city/state's zone change only needs editing here.
 */

// State -> primary IECC zone(s). Many states span 2 zones; "primary" reflects
// the dominant zone for the most-populated areas. Source: 2021 IECC climate
// zone map.
export const stateZones: Record<number, string[]> = {
  1: ['Hawaii', 'Puerto Rico', 'U.S. Virgin Islands', 'Guam'],
  2: ['Florida (peninsula)', 'Texas (south)', 'Louisiana (south)'],
  3: [
    'Alabama',
    'Arkansas',
    'Arizona (Phoenix/Tucson)',
    'California (south & central)',
    'Georgia',
    'Mississippi',
    'Nevada (Las Vegas)',
    'New Mexico (south)',
    'North Carolina (east)',
    'Oklahoma (east)',
    'South Carolina',
    'Tennessee (west)',
    'Texas (north)',
  ],
  4: [
    'California (north)',
    'Delaware',
    'District of Columbia',
    'Kansas',
    'Kentucky',
    'Maryland',
    'Missouri',
    'New Jersey',
    'New Mexico (north)',
    'New York (south)',
    'North Carolina (west)',
    'Ohio (south)',
    'Oklahoma (west)',
    'Oregon (Portland, Marine 4C)',
    'Pennsylvania (south)',
    'Tennessee (east)',
    'Virginia',
    'Washington (Puget Sound, Marine 4C)',
    'West Virginia',
  ],
  5: [
    'Colorado',
    'Connecticut',
    'Idaho (south)',
    'Illinois',
    'Indiana',
    'Iowa',
    'Massachusetts',
    'Michigan (south)',
    'Nebraska',
    'Nevada (Reno/north)',
    'New York (north)',
    'Ohio (north)',
    'Pennsylvania (north)',
    'Rhode Island',
    'Utah',
    'Washington (east)',
    'Wyoming (south)',
  ],
  6: [
    'Idaho (north)',
    'Maine',
    'Michigan (north)',
    'Minnesota (south)',
    'Montana',
    'New Hampshire',
    'North Dakota (south)',
    'South Dakota',
    'Vermont',
    'Wisconsin',
    'Wyoming (north)',
  ],
  7: [
    'Alaska (interior south)',
    'Minnesota (far north)',
    'North Dakota (north)',
  ],
  8: ['Alaska (interior north)'],
}

export interface CityZone {
  city: string
  state: string
  zone: number
}

// Major US cities mapped to IECC climate zone. 53 cities covering all 8 zones,
// chosen by population + geographic spread. Verified against 2021 IECC zone map.
export const majorCities: CityZone[] = [
  { city: 'Albuquerque', state: 'NM', zone: 4 },
  { city: 'Anchorage', state: 'AK', zone: 7 },
  { city: 'Atlanta', state: 'GA', zone: 3 },
  { city: 'Austin', state: 'TX', zone: 2 },
  { city: 'Baltimore', state: 'MD', zone: 4 },
  { city: 'Bismarck', state: 'ND', zone: 6 },
  { city: 'Boise', state: 'ID', zone: 5 },
  { city: 'Boston', state: 'MA', zone: 5 },
  { city: 'Buffalo', state: 'NY', zone: 5 },
  { city: 'Charlotte', state: 'NC', zone: 3 },
  { city: 'Chicago', state: 'IL', zone: 5 },
  { city: 'Cincinnati', state: 'OH', zone: 4 },
  { city: 'Cleveland', state: 'OH', zone: 5 },
  { city: 'Columbus', state: 'OH', zone: 5 },
  { city: 'Dallas', state: 'TX', zone: 3 },
  { city: 'Denver', state: 'CO', zone: 5 },
  { city: 'Detroit', state: 'MI', zone: 5 },
  { city: 'El Paso', state: 'TX', zone: 3 },
  { city: 'Fargo', state: 'ND', zone: 7 },
  { city: 'Fresno', state: 'CA', zone: 3 },
  { city: 'Honolulu', state: 'HI', zone: 1 },
  { city: 'Houston', state: 'TX', zone: 2 },
  { city: 'Indianapolis', state: 'IN', zone: 5 },
  { city: 'Jacksonville', state: 'FL', zone: 2 },
  { city: 'Kansas City', state: 'MO', zone: 4 },
  { city: 'Las Vegas', state: 'NV', zone: 3 },
  { city: 'Los Angeles', state: 'CA', zone: 3 },
  { city: 'Louisville', state: 'KY', zone: 4 },
  { city: 'Memphis', state: 'TN', zone: 3 },
  { city: 'Miami', state: 'FL', zone: 1 },
  { city: 'Milwaukee', state: 'WI', zone: 6 },
  { city: 'Minneapolis', state: 'MN', zone: 6 },
  { city: 'Nashville', state: 'TN', zone: 4 },
  { city: 'New Orleans', state: 'LA', zone: 2 },
  { city: 'New York', state: 'NY', zone: 4 },
  { city: 'Oklahoma City', state: 'OK', zone: 3 },
  { city: 'Omaha', state: 'NE', zone: 5 },
  { city: 'Orlando', state: 'FL', zone: 2 },
  { city: 'Philadelphia', state: 'PA', zone: 4 },
  { city: 'Phoenix', state: 'AZ', zone: 2 },
  { city: 'Pittsburgh', state: 'PA', zone: 5 },
  { city: 'Portland', state: 'OR', zone: 4 },
  { city: 'Raleigh', state: 'NC', zone: 4 },
  { city: 'Reno', state: 'NV', zone: 5 },
  { city: 'Sacramento', state: 'CA', zone: 3 },
  { city: 'Salt Lake City', state: 'UT', zone: 5 },
  { city: 'San Antonio', state: 'TX', zone: 2 },
  { city: 'San Diego', state: 'CA', zone: 3 },
  { city: 'San Francisco', state: 'CA', zone: 3 },
  { city: 'Seattle', state: 'WA', zone: 4 },
  { city: 'St. Louis', state: 'MO', zone: 4 },
  { city: 'Tampa', state: 'FL', zone: 2 },
  { city: 'Tucson', state: 'AZ', zone: 2 },
  { city: 'Washington', state: 'DC', zone: 4 },
]
